### ISSUE TITLE
config overwrite and MPI

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/docs#62]
Hello
`scipion3 config --overwrite` deletes the CONDA_ACTIVATION_CMD and nothing works after that.

These lines point to the wrong place for Ubuntu 20 (the most used Linux system today)
MPI_BINDIR = /usr/lib64/mpi/gcc/openmpi/bin
MPI_LIBDIR = /usr/lib64/mpi/gcc/openmpi/lib
MPI_INCLUDE = /usr/lib64/mpi/gcc/openmpi/include

My experience: you don't need these lines at all.

**Comment by MohamadHarastani** [comment]
I am talking about the installation documentation
https://github.com/scipion-em/docs/blob/release-3.0.0/docs/scipion-modes/how-to-install.rst

**Comment by MohamadHarastani** [comment]
Now as I am in scipion-em, I could notify you with that @pconesa :-)

**Comment by pconesa** [comment]
Good point, --overwrite should not ruin CONDA_ACTIVATION_CMD

**Comment by pconesa** [comment]
What about getting rid of --overwrite (at least for scipion.conf) It does not make sense anymore to have a template for it.

**Comment by pconesa** [comment]
@azazellochg ? I'm sure you want to say something about this.

**Comment by pconesa** [comment]
/path/for/scipion/scipion3 config --overwrite this is the reason to loose conda activation cmd.

**Comment by azazellochg** [comment]
Good point about conda var!
For the overwrite, I guess we can delete this flag. But then a user shouldn't complain when using broken config with a new installation :)

The most used linux system today is Android :smile: 

For the MPI and CUDA vars I believe it's a better practice to put the correct vars rather than nothing (which still gets default values from pwem.Config), as we had a lot of cluster users complain about configuration.

**Comment by pconesa** [comment]
Ok, the --overwrite for scipion.conf is actually going to code default values in the Config objects.... so, the thing is that CONDA_ACTIVATION_CMD is not part of any. 

I can make it part of pyworkflow.Config and should be fine

**Comment by azazellochg** [comment]
CONDA_ACTIVATION_CMD issue was fixed in https://github.com/scipion-em/scipion-pyworkflow/pull/408

**Comment by azazellochg** [comment]
unfortunately, I have no idea where modern Ubuntu installs openmpi files

**Comment by pconesa** [comment]
Good catch!, I guess we can close this. 

MPI SUFF can remain at least as a placeholder for the right paths upon modification.
